-- Period Close & Reporting Schema
-- Handles period closing process, closing entries, and financial reporting

-- Create schema
CREATE SCHEMA IF NOT EXISTS close;

-- Enums
CREATE TYPE close.period_status AS ENUM ('open', 'soft_closed', 'hard_closed');
CREATE TYPE close.close_type AS ENUM ('period', 'quarter', 'year');
CREATE TYPE close.close_rule_type AS ENUM ('income_summary', 'retained_earnings', 'reclassification', 'accrual_reversal', 'currency_revaluation');
CREATE TYPE close.close_run_status AS ENUM ('pending', 'processing', 'completed', 'failed', 'reversed');
CREATE TYPE close.report_type AS ENUM ('trial_balance', 'income_statement', 'balance_sheet', 'cash_flow', 'changes_in_equity', 'general_ledger', 'subsidiary_ledger', 'aging', 'custom');
CREATE TYPE close.report_format AS ENUM ('summary', 'detailed', 'comparative', 'consolidated');
CREATE TYPE close.report_status AS ENUM ('pending', 'generating', 'completed', 'failed');

-- Period Close Status Table
-- Tracks the close status of each fiscal period
CREATE TABLE close.period_close_status (
    id CHAR(26) PRIMARY KEY,
    entity_id CHAR(26) NOT NULL REFERENCES entities(id),
    fiscal_period_id CHAR(26) NOT NULL,
    fiscal_year_id CHAR(26) NOT NULL,
    status close.period_status NOT NULL DEFAULT 'open',
    soft_closed_at TIMESTAMPTZ,
    soft_closed_by CHAR(26),
    hard_closed_at TIMESTAMPTZ,
    hard_closed_by CHAR(26),
    reopened_at TIMESTAMPTZ,
    reopened_by CHAR(26),
    reopen_reason TEXT,
    closing_journal_entry_id CHAR(26),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(entity_id, fiscal_period_id)
);

-- Close Rules Table
-- Defines rules for generating closing entries
CREATE TABLE close.close_rules (
    id CHAR(26) PRIMARY KEY,
    entity_id CHAR(26) NOT NULL REFERENCES entities(id),
    rule_code VARCHAR(20) NOT NULL,
    rule_name VARCHAR(100) NOT NULL,
    rule_type close.close_rule_type NOT NULL,
    close_type close.close_type NOT NULL,
    sequence_number INTEGER NOT NULL DEFAULT 1,
    source_account_type VARCHAR(20), -- revenue, expense, etc.
    source_account_id CHAR(26), -- specific account if applicable
    target_account_id CHAR(26) NOT NULL, -- income summary or retained earnings
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(entity_id, rule_code)
);

-- Close Runs Table
-- Tracks each closing process execution
CREATE TABLE close.close_runs (
    id CHAR(26) PRIMARY KEY,
    entity_id CHAR(26) NOT NULL REFERENCES entities(id),
    run_number VARCHAR(30) NOT NULL,
    close_type close.close_type NOT NULL,
    fiscal_period_id CHAR(26) NOT NULL,
    fiscal_year_id CHAR(26) NOT NULL,
    close_date DATE NOT NULL,
    status close.close_run_status NOT NULL DEFAULT 'pending',
    rules_executed INTEGER NOT NULL DEFAULT 0,
    entries_created INTEGER NOT NULL DEFAULT 0,
    total_debits DECIMAL(19,4) NOT NULL DEFAULT 0,
    total_credits DECIMAL(19,4) NOT NULL DEFAULT 0,
    currency_code CHAR(3) NOT NULL,
    closing_journal_entry_id CHAR(26),
    reversal_journal_entry_id CHAR(26),
    initiated_by CHAR(26) NOT NULL,
    completed_at TIMESTAMPTZ,
    reversed_at TIMESTAMPTZ,
    reversed_by CHAR(26),
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(entity_id, run_number)
);

-- Close Run Entries Table
-- Individual closing entries generated by a close run
CREATE TABLE close.close_run_entries (
    id CHAR(26) PRIMARY KEY,
    close_run_id CHAR(26) NOT NULL REFERENCES close.close_runs(id),
    close_rule_id CHAR(26) NOT NULL REFERENCES close.close_rules(id),
    sequence_number INTEGER NOT NULL,
    source_account_id CHAR(26) NOT NULL,
    source_account_code VARCHAR(20) NOT NULL,
    source_account_name VARCHAR(100) NOT NULL,
    target_account_id CHAR(26) NOT NULL,
    target_account_code VARCHAR(20) NOT NULL,
    target_account_name VARCHAR(100) NOT NULL,
    amount DECIMAL(19,4) NOT NULL,
    currency_code CHAR(3) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Report Templates Table
-- Defines report layouts and configurations
CREATE TABLE close.report_templates (
    id CHAR(26) PRIMARY KEY,
    entity_id CHAR(26) REFERENCES entities(id), -- NULL for system templates
    template_code VARCHAR(30) NOT NULL,
    template_name VARCHAR(100) NOT NULL,
    report_type close.report_type NOT NULL,
    report_format close.report_format NOT NULL DEFAULT 'summary',
    is_system_template BOOLEAN NOT NULL DEFAULT false,
    configuration JSONB NOT NULL DEFAULT '{}',
    -- Configuration can include:
    -- - account_ranges: [{from: "1000", to: "1999", label: "Current Assets"}]
    -- - groupings: ["account_type", "cost_center"]
    -- - columns: ["budget", "actual", "variance", "prior_year"]
    -- - filters: {account_types: [...], cost_centers: [...]}
    -- - subtotals: [{level: 1, label: "Total Assets"}]
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Report Runs Table
-- Tracks generated reports
CREATE TABLE close.report_runs (
    id CHAR(26) PRIMARY KEY,
    entity_id CHAR(26) NOT NULL REFERENCES entities(id),
    report_number VARCHAR(30) NOT NULL,
    template_id CHAR(26) REFERENCES close.report_templates(id),
    report_type close.report_type NOT NULL,
    report_format close.report_format NOT NULL,
    report_name VARCHAR(200) NOT NULL,
    fiscal_period_id CHAR(26),
    fiscal_year_id CHAR(26),
    as_of_date DATE NOT NULL,
    comparison_period_id CHAR(26), -- for comparative reports
    comparison_year_id CHAR(26),
    parameters JSONB NOT NULL DEFAULT '{}',
    status close.report_status NOT NULL DEFAULT 'pending',
    generated_by CHAR(26) NOT NULL,
    generated_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Report Data Table
-- Stores the actual report data rows
CREATE TABLE close.report_data (
    id CHAR(26) PRIMARY KEY,
    report_run_id CHAR(26) NOT NULL REFERENCES close.report_runs(id) ON DELETE CASCADE,
    row_number INTEGER NOT NULL,
    row_type VARCHAR(20) NOT NULL, -- header, detail, subtotal, total, blank
    indent_level INTEGER NOT NULL DEFAULT 0,
    account_id CHAR(26),
    account_code VARCHAR(20),
    account_name VARCHAR(100),
    description VARCHAR(200),
    cost_center_id CHAR(26),
    cost_center_code VARCHAR(20),
    amount_1 DECIMAL(19,4), -- current period/YTD
    amount_2 DECIMAL(19,4), -- budget or prior period
    amount_3 DECIMAL(19,4), -- variance or prior year
    amount_4 DECIMAL(19,4), -- variance percent or other
    amount_5 DECIMAL(19,4), -- additional column
    currency_code CHAR(3),
    is_bold BOOLEAN NOT NULL DEFAULT false,
    is_underlined BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Scheduled Reports Table
-- For recurring report generation
CREATE TABLE close.scheduled_reports (
    id CHAR(26) PRIMARY KEY,
    entity_id CHAR(26) NOT NULL REFERENCES entities(id),
    template_id CHAR(26) NOT NULL REFERENCES close.report_templates(id),
    schedule_name VARCHAR(100) NOT NULL,
    frequency VARCHAR(20) NOT NULL, -- daily, weekly, monthly, quarterly, yearly
    day_of_week INTEGER, -- 0-6 for weekly
    day_of_month INTEGER, -- 1-31 for monthly
    parameters JSONB NOT NULL DEFAULT '{}',
    recipients JSONB NOT NULL DEFAULT '[]', -- email addresses or user IDs
    output_format VARCHAR(20) NOT NULL DEFAULT 'pdf', -- pdf, excel, csv
    is_active BOOLEAN NOT NULL DEFAULT true,
    last_run_at TIMESTAMPTZ,
    next_run_at TIMESTAMPTZ,
    created_by CHAR(26) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Year End Checklist Table
-- Tracks completion of year-end closing tasks
CREATE TABLE close.year_end_checklists (
    id CHAR(26) PRIMARY KEY,
    entity_id CHAR(26) NOT NULL REFERENCES entities(id),
    fiscal_year_id CHAR(26) NOT NULL,
    checklist_name VARCHAR(100) NOT NULL DEFAULT 'Year-End Close',
    status VARCHAR(20) NOT NULL DEFAULT 'in_progress',
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    completed_by CHAR(26),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(entity_id, fiscal_year_id)
);

-- Year End Checklist Items Table
CREATE TABLE close.year_end_checklist_items (
    id CHAR(26) PRIMARY KEY,
    checklist_id CHAR(26) NOT NULL REFERENCES close.year_end_checklists(id) ON DELETE CASCADE,
    sequence_number INTEGER NOT NULL,
    item_code VARCHAR(30) NOT NULL,
    item_name VARCHAR(200) NOT NULL,
    description TEXT,
    is_required BOOLEAN NOT NULL DEFAULT true,
    is_completed BOOLEAN NOT NULL DEFAULT false,
    completed_at TIMESTAMPTZ,
    completed_by CHAR(26),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_period_close_status_entity ON close.period_close_status(entity_id);
CREATE INDEX idx_period_close_status_period ON close.period_close_status(fiscal_period_id);
CREATE INDEX idx_period_close_status_year ON close.period_close_status(fiscal_year_id);
CREATE INDEX idx_period_close_status_status ON close.period_close_status(status);

CREATE INDEX idx_close_rules_entity ON close.close_rules(entity_id);
CREATE INDEX idx_close_rules_type ON close.close_rules(rule_type);
CREATE INDEX idx_close_rules_active ON close.close_rules(entity_id, is_active);

CREATE INDEX idx_close_runs_entity ON close.close_runs(entity_id);
CREATE INDEX idx_close_runs_period ON close.close_runs(fiscal_period_id);
CREATE INDEX idx_close_runs_year ON close.close_runs(fiscal_year_id);
CREATE INDEX idx_close_runs_status ON close.close_runs(status);

CREATE INDEX idx_close_run_entries_run ON close.close_run_entries(close_run_id);
CREATE INDEX idx_close_run_entries_rule ON close.close_run_entries(close_rule_id);

CREATE INDEX idx_report_templates_entity ON close.report_templates(entity_id);
CREATE INDEX idx_report_templates_type ON close.report_templates(report_type);
CREATE INDEX idx_report_templates_system ON close.report_templates(is_system_template);

CREATE INDEX idx_report_runs_entity ON close.report_runs(entity_id);
CREATE INDEX idx_report_runs_template ON close.report_runs(template_id);
CREATE INDEX idx_report_runs_type ON close.report_runs(report_type);
CREATE INDEX idx_report_runs_status ON close.report_runs(status);
CREATE INDEX idx_report_runs_date ON close.report_runs(as_of_date);

CREATE INDEX idx_report_data_run ON close.report_data(report_run_id);
CREATE INDEX idx_report_data_row ON close.report_data(report_run_id, row_number);

CREATE INDEX idx_scheduled_reports_entity ON close.scheduled_reports(entity_id);
CREATE INDEX idx_scheduled_reports_template ON close.scheduled_reports(template_id);
CREATE INDEX idx_scheduled_reports_next ON close.scheduled_reports(next_run_at);

CREATE INDEX idx_year_end_checklists_entity ON close.year_end_checklists(entity_id);
CREATE INDEX idx_year_end_checklists_year ON close.year_end_checklists(fiscal_year_id);

CREATE INDEX idx_year_end_checklist_items_checklist ON close.year_end_checklist_items(checklist_id);

-- Trigger for updated_at
CREATE TRIGGER update_period_close_status_updated_at BEFORE UPDATE ON close.period_close_status
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_close_rules_updated_at BEFORE UPDATE ON close.close_rules
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_close_runs_updated_at BEFORE UPDATE ON close.close_runs
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_report_templates_updated_at BEFORE UPDATE ON close.report_templates
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_scheduled_reports_updated_at BEFORE UPDATE ON close.scheduled_reports
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_year_end_checklists_updated_at BEFORE UPDATE ON close.year_end_checklists
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_year_end_checklist_items_updated_at BEFORE UPDATE ON close.year_end_checklist_items
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Run Number Generation Function
CREATE OR REPLACE FUNCTION close.generate_close_run_number(p_entity_id CHAR(26), p_prefix VARCHAR(10))
RETURNS VARCHAR(30) AS $$
DECLARE
    v_year TEXT;
    v_sequence INTEGER;
    v_run_number VARCHAR(30);
BEGIN
    v_year := TO_CHAR(CURRENT_DATE, 'YYYY');

    SELECT COALESCE(MAX(
        CAST(SUBSTRING(run_number FROM LENGTH(p_prefix) + 6 FOR 6) AS INTEGER)
    ), 0) + 1
    INTO v_sequence
    FROM close.close_runs
    WHERE entity_id = p_entity_id
    AND run_number LIKE p_prefix || v_year || '%';

    v_run_number := p_prefix || v_year || '-' || LPAD(v_sequence::TEXT, 6, '0');

    RETURN v_run_number;
END;
$$ LANGUAGE plpgsql;

-- Report Number Generation Function
CREATE OR REPLACE FUNCTION close.generate_report_number(p_entity_id CHAR(26), p_prefix VARCHAR(10))
RETURNS VARCHAR(30) AS $$
DECLARE
    v_year TEXT;
    v_sequence INTEGER;
    v_report_number VARCHAR(30);
BEGIN
    v_year := TO_CHAR(CURRENT_DATE, 'YYYY');

    SELECT COALESCE(MAX(
        CAST(SUBSTRING(report_number FROM LENGTH(p_prefix) + 6 FOR 6) AS INTEGER)
    ), 0) + 1
    INTO v_sequence
    FROM close.report_runs
    WHERE entity_id = p_entity_id
    AND report_number LIKE p_prefix || v_year || '%';

    v_report_number := p_prefix || v_year || '-' || LPAD(v_sequence::TEXT, 6, '0');

    RETURN v_report_number;
END;
$$ LANGUAGE plpgsql;

-- Insert System Report Templates
INSERT INTO close.report_templates (id, entity_id, template_code, template_name, report_type, report_format, is_system_template, configuration) VALUES
    ('01SYSTEM0TRIALBALANCE00001', NULL, 'SYS-TB', 'Trial Balance', 'trial_balance', 'detailed', true,
     '{"columns": ["account_code", "account_name", "debit", "credit"], "show_zero_balances": false}'),
    ('01SYSTEM0INCOMESTATEMENT01', NULL, 'SYS-IS', 'Income Statement', 'income_statement', 'summary', true,
     '{"sections": ["revenue", "expenses", "net_income"], "show_percentages": true}'),
    ('01SYSTEM0BALANCESHEET00001', NULL, 'SYS-BS', 'Balance Sheet', 'balance_sheet', 'summary', true,
     '{"sections": ["assets", "liabilities", "equity"], "show_prior_period": true}'),
    ('01SYSTEM0CASHFLOW00000001', NULL, 'SYS-CF', 'Cash Flow Statement', 'cash_flow', 'summary', true,
     '{"method": "indirect", "sections": ["operating", "investing", "financing"]}'),
    ('01SYSTEM0EQUITYCHANGES001', NULL, 'SYS-EQ', 'Statement of Changes in Equity', 'changes_in_equity', 'detailed', true,
     '{"columns": ["common_stock", "retained_earnings", "other_equity", "total"]}');

-- RLS Policies
ALTER TABLE close.period_close_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE close.close_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE close.close_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE close.close_run_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE close.report_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE close.report_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE close.report_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE close.scheduled_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE close.year_end_checklists ENABLE ROW LEVEL SECURITY;
ALTER TABLE close.year_end_checklist_items ENABLE ROW LEVEL SECURITY;

-- RLS Policies for period_close_status
CREATE POLICY period_close_status_entity_isolation ON close.period_close_status
    USING (entity_id = current_setting('app.current_entity_id', true)::CHAR(26));

-- RLS Policies for close_rules
CREATE POLICY close_rules_entity_isolation ON close.close_rules
    USING (entity_id = current_setting('app.current_entity_id', true)::CHAR(26));

-- RLS Policies for close_runs
CREATE POLICY close_runs_entity_isolation ON close.close_runs
    USING (entity_id = current_setting('app.current_entity_id', true)::CHAR(26));

-- RLS Policies for close_run_entries (through parent)
CREATE POLICY close_run_entries_entity_isolation ON close.close_run_entries
    USING (close_run_id IN (
        SELECT id FROM close.close_runs
        WHERE entity_id = current_setting('app.current_entity_id', true)::CHAR(26)
    ));

-- RLS Policies for report_templates (system templates visible to all)
CREATE POLICY report_templates_entity_isolation ON close.report_templates
    USING (is_system_template = true OR entity_id = current_setting('app.current_entity_id', true)::CHAR(26));

-- RLS Policies for report_runs
CREATE POLICY report_runs_entity_isolation ON close.report_runs
    USING (entity_id = current_setting('app.current_entity_id', true)::CHAR(26));

-- RLS Policies for report_data (through parent)
CREATE POLICY report_data_entity_isolation ON close.report_data
    USING (report_run_id IN (
        SELECT id FROM close.report_runs
        WHERE entity_id = current_setting('app.current_entity_id', true)::CHAR(26)
    ));

-- RLS Policies for scheduled_reports
CREATE POLICY scheduled_reports_entity_isolation ON close.scheduled_reports
    USING (entity_id = current_setting('app.current_entity_id', true)::CHAR(26));

-- RLS Policies for year_end_checklists
CREATE POLICY year_end_checklists_entity_isolation ON close.year_end_checklists
    USING (entity_id = current_setting('app.current_entity_id', true)::CHAR(26));

-- RLS Policies for year_end_checklist_items (through parent)
CREATE POLICY year_end_checklist_items_entity_isolation ON close.year_end_checklist_items
    USING (checklist_id IN (
        SELECT id FROM close.year_end_checklists
        WHERE entity_id = current_setting('app.current_entity_id', true)::CHAR(26)
    ));
